export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const SET_ENTITIES = 'SET_ENTITIES';
export const SET_SELECTED_ENTITY = 'SET_SELECTED_ENTITY';
export const CLEAR_SELECTED_ENTITY = 'CLEAR_SELECTED_ENTITY';
export const FAILED_GETTING_ENTITIES = 'FAILED_GETTING_ENTITIES';
